// packages/react/src/components/accordion/Accordion.tsx
import * as React from 'react'
import * as AccordionPrimitive from '@radix-ui/react-accordion'
import { ChevronDown } from 'lucide-react'
import { cn } from '@/lib/utils'

const Accordion = AccordionPrimitive.Root

const AccordionItem = React.forwardRef<
  React.ElementRef<typeof AccordionPrimitive.Item>,
  React.ComponentPropsWithoutRef<typeof AccordionPrimitive.Item>
>(({ className, ...props }, ref) => (
  <AccordionPrimitive.Item
    ref={ref}
    className={cn('border-b', className)}
    {...props}
  />
))
AccordionItem.displayName = 'AccordionItem'

const AccordionTrigger = React.forwardRef<
  React.ElementRef<typeof AccordionPrimitive.Trigger>,
  React.ComponentPropsWithoutRef<typeof AccordionPrimitive.Trigger>
>(({ className, children, ...props }, ref) => (
  <AccordionPrimitive.Header className="flex">
    <AccordionPrimitive.Trigger
      ref={ref}
      className={cn(
        'flex flex-1 items-center justify-between py-4 font-medium transition-all hover:underline [&[data-state=open]>svg]:rotate-180',
        className
      )}
      {...props}
    >
      {children}
      <ChevronDown className="h-4 w-4 shrink-0 transition-transform duration-200" />
    </AccordionPrimitive.Trigger>
  </AccordionPrimitive.Header>
))
AccordionTrigger.displayName = AccordionPrimitive.Trigger.displayName

const AccordionContent = React.forwardRef<
  React.ElementRef<typeof AccordionPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof AccordionPrimitive.Content>
>(({ className, children, ...props }, ref) => (
  <AccordionPrimitive.Content
    ref={ref}
    className={cn(
      'overflow-hidden text-sm transition-all data-[state=closed]:animate-accordion-up data-[state=open]:animate-accordion-down',
      className
    )}
    {...props}
  >
    <div className="pb-4 pt-0">{children}</div>
  </AccordionPrimitive.Content>
))
AccordionContent.displayName = AccordionPrimitive.Content.displayName

export { Accordion, AccordionItem, AccordionTrigger, AccordionContent }

// packages/angular/src/components/accordion/accordion.component.ts
import { Component, Input, Output, EventEmitter, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  RdxAccordionRootDirective,
  RdxAccordionItemDirective,
  RdxAccordionTriggerDirective,
  RdxAccordionContentDirective,
} from '@radix-ng/primitives/accordion';
import { cn } from '@/lib/utils';

@Component({
  selector: 'ui-accordion',
  standalone: true,
  imports: [CommonModule, RdxAccordionRootDirective],
  template: `
    <div
      rdxAccordionRoot
      [rdxAccordionType]="type"
      [rdxAccordionValue]="value"
      (rdxAccordionValueChange)="onValueChange($event)"
      [class]="accordionClasses"
    >
      <ng-content></ng-content>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AccordionComponent {
  @Input() type: 'single' | 'multiple' = 'single';
  @Input() value?: string | string[];
  @Input() class?: string;
  @Output() valueChange = new EventEmitter<string | string[]>();

  get accordionClasses(): string {
    return cn('', this.class);
  }

  onValueChange(value: string | string[]): void {
    this.value = value;
    this.valueChange.emit(value);
  }
}

@Component({
  selector: 'ui-accordion-item',
  standalone: true,
  imports: [CommonModule, RdxAccordionItemDirective],
  template: `
    <div rdxAccordionItem [rdxAccordionItemValue]="value" [class]="itemClasses">
      <ng-content></ng-content>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AccordionItemComponent {
  @Input() value!: string;
  @Input() class?: string;

  get itemClasses(): string {
    return cn('border-b', this.class);
  }
}

@Component({
  selector: 'ui-accordion-trigger',
  standalone: true,
  imports: [CommonModule, RdxAccordionTriggerDirective],
  template: `
    <h3 class="flex">
      <button rdxAccordionTrigger [class]="triggerClasses">
        <ng-content></ng-content>
        <svg
          class="h-4 w-4 shrink-0 transition-transform duration-200"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
        >
          <polyline points="6 9 12 15 18 9"></polyline>
        </svg>
      </button>
    </h3>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AccordionTriggerComponent {
  @Input() class?: string;

  get triggerClasses(): string {
    return cn(
      'flex flex-1 items-center justify-between py-4 font-medium transition-all hover:underline [&[data-state=open]>svg]:rotate-180',
      this.class
    );
  }
}

@Component({
  selector: 'ui-accordion-content',
  standalone: true,
  imports: [CommonModule, RdxAccordionContentDirective],
  template: `
    <div rdxAccordionContent [class]="contentClasses">
      <div class="pb-4 pt-0">
        <ng-content></ng-content>
      </div>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AccordionContentComponent {
  @Input() class?: string;

  get contentClasses(): string {
    return cn(
      'overflow-hidden text-sm transition-all data-[state=closed]:animate-accordion-up data-[state=open]:animate-accordion-down',
      this.class
    );
  }
}
