// packages/react/src/components/menubar/Menubar.tsx
import * as React from 'react'
import * as MenubarPrimitive from '@radix-ui/react-menubar'
import { cn } from '@/lib/utils'

const Menubar = React.forwardRef<
  React.ElementRef<typeof MenubarPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof MenubarPrimitive.Root>
>(({ className, ...props }, ref) => (
  <MenubarPrimitive.Root
    ref={ref}
    className={cn(
      'flex h-10 items-center space-x-1 rounded-md border bg-background p-1',
      className
    )}
    {...props}
  />
))
Menubar.displayName = MenubarPrimitive.Root.displayName

const MenubarMenu = MenubarPrimitive.Menu
const MenubarTrigger = MenubarPrimitive.Trigger
const MenubarContent = MenubarPrimitive.Content
const MenubarItem = MenubarPrimitive.Item
const MenubarSeparator = MenubarPrimitive.Separator

export { Menubar, MenubarMenu, MenubarTrigger, MenubarContent, MenubarItem, MenubarSeparator }

// packages/vue/src/components/menubar/Menubar.vue
<script setup lang="ts">
import { type HTMLAttributes, computed } from 'vue'
import { MenubarRoot, type MenubarRootProps } from 'radix-vue'
import { cn } from '@/lib/utils'

interface Props extends MenubarRootProps {
  class?: HTMLAttributes['class']
}

const props = defineProps<Props>()

const delegatedProps = computed(() => {
  const { class: _, ...delegated } = props
  return delegated
})
</script>

<template>
  <MenubarRoot
    :class="cn('flex h-10 items-center space-x-1 rounded-md border bg-background p-1', props.class)"
    v-bind="delegatedProps"
  >
    <slot />
  </MenubarRoot>
</template>
