// packages/vue/src/components/toolbar/Toolbar.vue
<script setup lang="ts">
import { cn } from '@/lib/utils'
import { Toolbar as ToolbarPrimitive } from 'radix-vue'

interface Props {
  class?: string
}

const props = defineProps<Props>()
</script>

<template>
  <ToolbarPrimitive
    :class="
      cn(
        'flex w-full min-w-max items-center gap-1 rounded-md bg-background p-1',
        props.class
      )
    "
  >
    <slot />
  </ToolbarPrimitive>
</template>

// packages/angular/src/components/toolbar/toolbar.component.ts
import { Component, Input } from '@angular/core'
import { cn } from '@/lib/utils'

@Component({
  selector: 'ui-toolbar',
  standalone: true,
  template: `
    <div [class]="className">
      <ng-content />
    </div>
  `,
})
export class ToolbarComponent {
  @Input() class?: string

  get className() {
    return cn(
      'flex w-full min-w-max items-center gap-1 rounded-md bg-background p-1',
      this.class
    )
  }
}
