// examples/react-example/components/ui/progress/Progress.tsx
import * as React from 'react';
import * as ProgressPrimitive from '@radix-ui/react-progress';
import { cn } from '@/lib/utils';

interface ProgressProps extends React.ComponentPropsWithoutRef<typeof ProgressPrimitive.Root> {
  value?: number;
  max?: number;
}

const Progress = React.forwardRef<
  React.ElementRef<typeof ProgressPrimitive.Root>,
  ProgressProps
>(({ className, value = 0, max = 100, ...props }, ref) => {
  const percentage = Math.min(Math.max((value / max) * 100, 0), 100);

  return (
    <ProgressPrimitive.Root
      ref={ref}
      className={cn(
        'relative h-2 w-full overflow-hidden rounded-full bg-secondary',
        className
      )}
      {...props}
    >
      <ProgressPrimitive.Indicator
        className="h-full w-full flex-1 bg-primary transition-all"
        style={{ transform: `translateX(-${100 - percentage}%)` }}
      />
    </ProgressPrimitive.Root>
  );
});

Progress.displayName = 'Progress';

export { Progress };

// packages/angular/src/components/progress/progress.component.ts
import { Component, Input, ChangeDetectionStrategy, computed, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  RdxProgressRootDirective,
  RdxProgressIndicatorDirective,
} from '@radix-ng/primitives/progress';
import { cn } from '@/lib/utils';

@Component({
  selector: 'ui-progress',
  standalone: true,
  imports: [CommonModule, RdxProgressRootDirective, RdxProgressIndicatorDirective],
  template: `
    <div
      rdxProgressRoot
      [rdxProgressValue]="value()"
      [rdxProgressMax]="max()"
      [class]="rootClasses()"
    >
      <div
        rdxProgressIndicator
        class="h-full w-full flex-1 bg-primary transition-all"
        [style.transform]="'translateX(-' + (100 - percentage()) + '%)'"
      ></div>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ProgressComponent {
  @Input() set value(val: number | null | undefined) {
    this._value.set(val ?? 0);
  }
  @Input() set max(val: number) {
    this._max.set(val);
  }
  @Input() class?: string;

  private _value = signal<number>(0);
  private _max = signal<number>(100);

  protected value = computed(() => this._value());
  protected max = computed(() => this._max());

  protected percentage = computed(() => {
    const val = this.value();
    const maxVal = this.max();
    return Math.min(Math.max((val / maxVal) * 100, 0), 100);
  });

  protected rootClasses = computed(() => {
    return cn(
      'relative h-2 w-full overflow-hidden rounded-full bg-secondary',
      this.class
    );
  });
}
