// packages/vue/src/components/skeleton/Skeleton.vue
<script setup lang="ts">
import { cn } from '@/lib/utils'
import { computed } from 'vue'

interface Props {
  /**
   * CSS class
   */
  class?: string
  /**
   * Skeleton variant
   * @default "default"
   */
  variant?: 'default' | 'circle' | 'text'
}

const props = withDefaults(defineProps<Props>(), {
  variant: 'default',
})

const className = computed(() =>
  cn(
    'animate-pulse bg-muted',
    {
      'rounded-md': props.variant === 'default',
      'rounded-full': props.variant === 'circle',
      'h-4 rounded': props.variant === 'text',
    },
    props.class
  )
)
</script>

<template>
  <div :class="className">
    <slot />
  </div>
</template>

// packages/react/src/components/skeleton/Skeleton.tsx
import * as React from 'react'
import { cn } from '@/lib/utils'

export interface SkeletonProps extends React.HTMLAttributes<HTMLDivElement> {
  /**
   * Skeleton variant
   * @default "default"
   */
  variant?: 'default' | 'circle' | 'text'
}

const Skeleton = React.forwardRef<HTMLDivElement, SkeletonProps>(
  ({ className, variant = 'default', ...props }, ref) => {
    return (
      <div
        ref={ref}
        className={cn(
          'animate-pulse bg-muted',
          {
            'rounded-md': variant === 'default',
            'rounded-full': variant === 'circle',
            'h-4 rounded': variant === 'text',
          },
          className
        )}
        {...props}
      />
    )
  }
)
Skeleton.displayName = 'Skeleton'

export { Skeleton }
