// packages/angular/src/components/tags-input/tags-input.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core'
import { CommonModule } from '@angular/common'
import { FormsModule } from '@angular/forms'
import { cn } from '@/lib/utils'

@Component({
  selector: 'ui-tags-input',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div
      [class]="containerClass"
      (click)="inputElement.focus()"
    >
      <span
        *ngFor="let tag of value"
        class="inline-flex items-center gap-1 rounded-md bg-primary px-2 py-1 text-xs font-medium text-primary-foreground"
      >
        {{ tag }}
        <button
          type="button"
          class="rounded-sm opacity-70 ring-offset-background transition-opacity hover:opacity-100 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2"
          (click)="removeTag(tag); $event.stopPropagation()"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="12"
            height="12"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            class="h-3 w-3"
          >
            <path d="M18 6 6 18" />
            <path d="m6 6 12 12" />
          </svg>
          <span class="sr-only">Remove {{ tag }}</span>
        </button>
      </span>
      <input
        #inputElement
        [(ngModel)]="inputValue"
        type="text"
        [placeholder]="value.length === 0 ? placeholder : ''"
        class="flex-1 bg-transparent outline-none placeholder:text-muted-foreground"
        (keydown)="handleKeyDown($event)"
      />
    </div>
  `,
})
export class TagsInputComponent {
  @Input() class?: string
  @Input() value: string[] = []
  @Input() placeholder: string = 'Add tag...'
  @Output() valueChange = new EventEmitter<string[]>()
  @Output() tagAdd = new EventEmitter<string>()
  @Output() tagRemove = new EventEmitter<string>()

  inputValue: string = ''

  get containerClass() {
    return cn(
      'flex min-h-10 w-full flex-wrap gap-2 rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-within:ring-2 focus-within:ring-ring focus-within:ring-offset-2',
      this.class
    )
  }

  handleKeyDown(e: KeyboardEvent) {
    if (e.key === 'Enter' && this.inputValue.trim()) {
      e.preventDefault()
      const newTag = this.inputValue.trim()
      if (!this.value.includes(newTag)) {
        const newTags = [...this.value, newTag]
        this.valueChange.emit(newTags)
        this.tagAdd.emit(newTag)
      }
      this.inputValue = ''
    } else if (e.key === 'Backspace' && !this.inputValue && this.value.length > 0) {
      const lastTag = this.value[this.value.length - 1]
      const newTags = this.value.slice(0, -1)
      this.valueChange.emit(newTags)
      this.tagRemove.emit(lastTag)
    }
  }

  removeTag(tagToRemove: string) {
    const newTags = this.value.filter((tag) => tag !== tagToRemove)
    this.valueChange.emit(newTags)
    this.tagRemove.emit(tagToRemove)
  }
}

// packages/vue/src/components/tags-input/TagsInput.vue
<script setup lang="ts">
import { cn } from '@/lib/utils'
import { ref } from 'vue'
import { X } from 'lucide-vue-next'

interface Props {
  class?: string
  modelValue?: string[]
  placeholder?: string
}

const props = withDefaults(defineProps<Props>(), {
  modelValue: () => [],
  placeholder: 'Add tag...',
})

const emit = defineEmits<{
  'update:modelValue': [value: string[]]
  tagAdd: [tag: string]
  tagRemove: [tag: string]
}>()

const inputValue = ref('')
const inputRef = ref<HTMLInputElement>()

const handleKeyDown = (e: KeyboardEvent) => {
  if (e.key === 'Enter' && inputValue.value.trim()) {
    e.preventDefault()
    const newTag = inputValue.value.trim()
    if (!props.modelValue.includes(newTag)) {
      const newTags = [...props.modelValue, newTag]
      emit('update:modelValue', newTags)
      emit('tagAdd', newTag)
    }
    inputValue.value = ''
  } else if (e.key === 'Backspace' && !inputValue.value && props.modelValue.length > 0) {
    const lastTag = props.modelValue[props.modelValue.length - 1]
    const newTags = props.modelValue.slice(0, -1)
    emit('update:modelValue', newTags)
    emit('tagRemove', lastTag)
  }
}

const removeTag = (tagToRemove: string) => {
  const newTags = props.modelValue.filter((tag) => tag !== tagToRemove)
  emit('update:modelValue', newTags)
  emit('tagRemove', tagToRemove)
}
</script>

<template>
  <div
    :class="
      cn(
        'flex min-h-10 w-full flex-wrap gap-2 rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-within:ring-2 focus-within:ring-ring focus-within:ring-offset-2',
        props.class
      )
    "
    @click="inputRef?.focus()"
  >
    <span
      v-for="tag in modelValue"
      :key="tag"
      class="inline-flex items-center gap-1 rounded-md bg-primary px-2 py-1 text-xs font-medium text-primary-foreground"
    >
      {{ tag }}
      <button
        type="button"
        class="rounded-sm opacity-70 ring-offset-background transition-opacity hover:opacity-100 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2"
        @click="removeTag(tag)"
      >
        <X class="h-3 w-3" />
        <span class="sr-only">Remove {{ tag }}</span>
      </button>
    </span>
    <input
      ref="inputRef"
      v-model="inputValue"
      type="text"
      :placeholder="modelValue.length === 0 ? placeholder : ''"
      class="flex-1 bg-transparent outline-none placeholder:text-muted-foreground"
      @keydown="handleKeyDown"
    />
  </div>
</template>
