// packages/vue/src/components/skeleton/Skeleton.vue
<script setup lang="ts">
import { cn } from '@/lib/utils'
import { computed } from 'vue'

interface Props {
  /**
   * CSS class
   */
  class?: string
  /**
   * Skeleton variant
   * @default "default"
   */
  variant?: 'default' | 'circle' | 'text'
}

const props = withDefaults(defineProps<Props>(), {
  variant: 'default',
})

const className = computed(() =>
  cn(
    'animate-pulse bg-muted',
    {
      'rounded-md': props.variant === 'default',
      'rounded-full': props.variant === 'circle',
      'h-4 rounded': props.variant === 'text',
    },
    props.class
  )
)
</script>

<template>
  <div :class="className">
    <slot />
  </div>
</template>

// packages/angular/src/components/skeleton/skeleton.component.ts
import { Component, Input } from '@angular/core'
import { cn } from '@/lib/utils'

@Component({
  selector: 'ui-skeleton',
  standalone: true,
  template: `
    <div [class]="className">
      <ng-content />
    </div>
  `,
})
export class SkeletonComponent {
  /**
   * CSS class
   */
  @Input() class?: string

  /**
   * Skeleton variant
   * @default "default"
   */
  @Input() variant: 'default' | 'circle' | 'text' = 'default'

  get className() {
    return cn(
      'animate-pulse bg-muted',
      {
        'rounded-md': this.variant === 'default',
        'rounded-full': this.variant === 'circle',
        'h-4 rounded': this.variant === 'text',
      },
      this.class
    )
  }
}
